### ISSUE TITLE
fixed issues raised in review!

### ISSUE THREAD

**Issue by Pruthv1** [hyginn/rete#57] opened 2017-03-28 14:44 UTC

**Comment by hyginn** [comment] 2017-03-29 06:40
Not sure what the issue is for ... ? 
I looked over your code - your fixing-of-issues seems almost complete. Good. When you are done, and this is ready to be merged in, raise another Issue, and paste an R CMD check output. Or were there questions?

**Closed by hyginn** 2017-03-29 06:40 UTC
