### ISSUE TITLE
R CMD check for importSNV

### ISSUE THREAD

**Issue by Pruthv1** [hyginn/rete#60] opened 2017-03-29 17:02 UTC
I made input test files and true output files separate.They are no longer created in the test itself since it was causing some issues during testing. 

Here is the R CMD output:

==> devtools::check(document = FALSE)

Setting env vars ---------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building rete ------------------------------------------------------------------
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD build '/home/pruthvi/Desktop/rete' --no-resave-data --no-manual 

* checking for file ‘/home/pruthvi/Desktop/rete/DESCRIPTION’ ... OK
* preparing ‘rete’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘rete_0.1.0.tar.gz’

Setting env vars ---------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_USE_ASPELL_: TRUE
_R_CHECK_CRAN_INCOMING_           : FALSE
_R_CHECK_FORCE_SUGGESTS_          : FALSE
Checking rete ------------------------------------------------------------------
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD check '/tmp/RtmpOsK71L/rete_0.1.0.tar.gz' --as-cran --timings  \
  --no-manual 

* using log directory ‘/home/pruthvi/Desktop/rete.Rcheck’
* using R version 3.3.3 (2017-03-06)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘rete/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘rete’ version ‘0.1.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘rete’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
.mafHeaderCheck: no visible global function definition for ‘read.table’
.rSNVheadercheck: no visible global function definition for
  ‘read.table’
importSNV.TCGA: no visible global function definition for ‘read.table’
importSNV.TCGA: no visible global function definition for
  ‘complete.cases’
importSNV.TCGA: no visible global function definition for ‘write.table’
Undefined global functions or variables:
  complete.cases read.table write.table
Consider adding
  importFrom("stats", "complete.cases")
  importFrom("utils", "read.table", "write.table")
to your NAMESPACE file.
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’ ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  
  Welcome to rete.
    Object details will be logged to
      "/home/pruthvi/Desktop/rete.Rcheck/tests/rete_2017-03-29.1.log"
    or type ?logfile for instructions to set a different name.
  
  
  > 
  > test_check("rete")
  Error in importNet.STRING(fName = "dataString.txt", net = "experimental",  : 
    .checkArgs> "fName" error: file "dataString.txt" does not exist.
  Calls: test_check ... force -> source_file -> eval -> eval -> importNet.STRING
  testthat results ================================================================
  OK: 0 SKIPPED: 0 FAILED: 0
  Execution halted
* DONE
Status: 1 ERROR, 1 NOTE
checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  
  Welcome to rete.
    Object details will be logged to
      "/home/pruthvi/Desktop/rete.Rcheck/tests/rete_2017-03-29.1.log"
    or type ?logfile for instructions to set a different name.
  
  
  > 
  > test_check("rete")
  Error in importNet.STRING(fName = "dataString.txt", net = "experimental",  : 
    .checkArgs> "fName" error: file "dataString.txt" does not exist.
  Calls: test_check ... force -> source_file -> eval -> eval -> importNet.STRING
  testthat results ================================================================
  OK: 0 SKIPPED: 0 FAILED: 0
  Execution halted

checking R code for possible problems ... NOTE
.mafHeaderCheck: no visible global function definition for ‘read.table’
.rSNVheadercheck: no visible global function definition for
  ‘read.table’
importSNV.TCGA: no visible global function definition for ‘read.table’
importSNV.TCGA: no visible global function definition for
  ‘complete.cases’
importSNV.TCGA: no visible global function definition for ‘write.table’
Undefined global functions or variables:
  complete.cases read.table write.table
Consider adding
  importFrom("stats", "complete.cases")
  importFrom("utils", "read.table", "write.table")
to your NAMESPACE file.

See
  ‘/home/pruthvi/Desktop/rete.Rcheck/00check.log’
for details.

R CMD check results
1 error  | 0 warnings | 1 note 

R CMD check succeeded

**Comment by RicardoRam** [comment] 2017-03-29 21:55
@hyginn I forked his repo to my computer and the CMD check passed. We aren't sure what the issue is. This is what I got. 

Setting env vars --------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building rete -----------------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' CMD build '/Users/Ricardo/Documents/School/Bioinformatics/BCB420Y1/testretes/rete' --no-resave-data --no-manual
* checking for file ‘/Users/Ricardo/Documents/School/Bioinformatics/BCB420Y1/testretes/rete/DESCRIPTION’ ... OK
* preparing ‘rete’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘rete_0.1.0.tar.gz’
Setting env vars --------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking rete -----------------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' CMD check '/var/folders/6y/28kg2jh55cxdwjwrr82cycs80000gn/T//Rtmp71dLBz/rete_0.1.0.tar.gz' --as-cran --timings --no-manual
* using log directory ‘/Users/Ricardo/Documents/School/Bioinformatics/BCB420Y1/testretes/rete.Rcheck’
* using R version 3.3.2 (2016-10-31)
* using platform: x86_64-apple-darwin13.4.0 (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘rete/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘rete’ version ‘0.1.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘rete’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
.mafHeaderCheck: no visible global function definition for ‘read.table’
.rSNVheadercheck: no visible global function definition for
  ‘read.table’
importSNV.TCGA: no visible global function definition for ‘read.table’
importSNV.TCGA: no visible global function definition for
  ‘complete.cases’
importSNV.TCGA: no visible global function definition for ‘write.table’
Undefined global functions or variables:
  complete.cases read.table write.table
Consider adding
  importFrom("stats", "complete.cases")
  importFrom("utils", "read.table", "write.table")
to your NAMESPACE file.
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... WARNING
Undocumented code objects:
  ‘importM.COSMIC’
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
 OK
* DONE
Status: 1 WARNING, 1 NOTE
checking for missing documentation entries ... WARNING
Undocumented code objects:
  ‘importM.COSMIC’
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.

checking R code for possible problems ... NOTE
.mafHeaderCheck: no visible global function definition for ‘read.table’
.rSNVheadercheck: no visible global function definition for
  ‘read.table’
importSNV.TCGA: no visible global function definition for ‘read.table’
importSNV.TCGA: no visible global function definition for
  ‘complete.cases’
importSNV.TCGA: no visible global function definition for ‘write.table’
Undefined global functions or variables:
  complete.cases read.table write.table
Consider adding
  importFrom("stats", "complete.cases")
  importFrom("utils", "read.table", "write.table")
to your NAMESPACE file.
R CMD check results
0 errors | 1 warning  | 1 note 

R CMD check succeeded

**Comment by hyginn** [comment] 2017-03-29 22:10
read.table() and write.table() are in the utils package. Use 
```
utils::read.table()
``` 
in the code, and I expect the problem to go away. complete.cases() is a function in the stats package. What is that doing here? I suspect unintended overwriting of an existing object name.

I don't have problems stemming from missing documentation for importM.COSMIC - try rebuilding the documentation (```devtools::document()```).

I can't tell at all why the test file for ```testImport.R``` is not found - that error should either not occur, or also occur for ```testImportM.COSMIC```. However, if this is not due to an obvious misconfiguration on Pruthvi's side, we need to make the way we find test-data more robust (eg. via ```system.file()```).

**Comment by Pruthv1** [comment] 2017-03-29 22:31
I asked Ricardo to check it and he did not get that error. I am not sure what is going wrong. I reinstalled R and rStudio.

**Comment by Pruthv1** [comment] 2017-03-29 22:43
I think the problem is just on my side. Here is the CMD check with the "notes" fixed and changes committed. ready to merge.


==> devtools::check(document = FALSE)

Setting env vars ---------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building rete ------------------------------------------------------------------
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD build '/home/pruthvi/Documents/rete' --no-resave-data --no-manual 

* checking for file ‘/home/pruthvi/Documents/rete/DESCRIPTION’ ... OK
* preparing ‘rete’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘rete_0.1.0.tar.gz’

Setting env vars ---------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_USE_ASPELL_: TRUE
_R_CHECK_CRAN_INCOMING_           : FALSE
_R_CHECK_FORCE_SUGGESTS_          : FALSE
Checking rete ------------------------------------------------------------------
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD check '/tmp/RtmpNQ1Nth/rete_0.1.0.tar.gz' --as-cran --timings  \
  --no-manual 

* using log directory ‘/home/pruthvi/Documents/rete.Rcheck’
* using R version 3.3.3 (2017-03-06)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘rete/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘rete’ version ‘0.1.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘rete’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  
  Welcome to rete.
    Object details will be logged to
      "/home/pruthvi/Documents/rete.Rcheck/tests/rete_2017-03-29.1.log"
    or type ?logfile for instructions to set a different name.
  
  
  > 
  > test_check("rete")
  Error in importNet.STRING(fName = "dataString.txt", net = "experimental",  : 
    .checkArgs> "fName" error: file "dataString.txt" does not exist.
  Calls: test_check ... force -> source_file -> eval -> eval -> importNet.STRING
  testthat results ================================================================
  OK: 0 SKIPPED: 0 FAILED: 0
  Execution halted
* DONE
Status: 1 ERROR
checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  
  Welcome to rete.
    Object details will be logged to
      "/home/pruthvi/Documents/rete.Rcheck/tests/rete_2017-03-29.1.log"
    or type ?logfile for instructions to set a different name.
  
  
  > 
  > test_check("rete")
  Error in importNet.STRING(fName = "dataString.txt", net = "experimental",  : 
    .checkArgs> "fName" error: file "dataString.txt" does not exist.
  Calls: test_check ... force -> source_file -> eval -> eval -> importNet.STRING
  testthat results ================================================================
  OK: 0 SKIPPED: 0 FAILED: 0
  Execution halted

See
  ‘/home/pruthvi/Documents/rete.Rcheck/00check.log’
for details.

R CMD check results
1 error  | 0 warnings | 0 notes

R CMD check succeeded

**Comment by hyginn** [comment] 2017-03-30 00:21
As I said - I don't see why other tests don't have the same problem. The STRING tests seem to work for me and others. Since I can't reproduce it, it should not be a roadblock for checking in the code. Open an Issue when it's ready to be checked in.

**Closed by hyginn** 2017-03-30 00:21 UTC
